CREATE TABLE IF NOT EXISTS data (
    id int(5) NOT NULL AUTO_INCREMENT,
    date DATE DEFAULT NOT NULL,
    temp int(5) NOT NULL AUTO_INCREMENT,
    hum int(5) NOT NULL AUTO_INCREMENT,
    pressure int(5) NOT NULL AUTO_INCREMENT,
    PRIMARY KEY(id)
);

CREATE TABLE log (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	created_date TIMESTAMP,
	temperature DECIMAL(5,2) NOT NULL,
	pressure DECIMAL(5,2) NOT NULL,
	humidity DECIMAL(5,2) NOT NULL
);